# Generated by Django 5.0 on 2023-12-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='img',
        ),
        migrations.RemoveField(
            model_name='model',
            name='price',
        ),
    ]
