# Generated by Django 5.0 on 2023-12-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_client1_client2_fermer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Late',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='index/img')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
