# Generated by Django 5.0 on 2023-12-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_late'),
    ]

    operations = [
        migrations.CreateModel(
            name='We',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='about/img')),
                ('bio', models.TextField()),
            ],
        ),
    ]
