# Generated by Django 5.0 on 2023-12-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.ImageField(upload_to='')),
                ('img', models.ImageField(upload_to='product/img')),
            ],
        ),
    ]
