# Generated by Django 5.0 on 2023-12-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_our'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our',
            name='price',
            field=models.IntegerField(),
        ),
    ]
