# Generated by Django 5.0 on 2024-01-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='late',
            name='bio',
        ),
        migrations.AddField(
            model_name='late',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='late',
            name='slug',
            field=models.SlugField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='late',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='late',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
