# Generated by Django 5.0 on 2024-01-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_late_bio_late_price_late_slug_alter_late_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
